application: healthy-planet-compute
version: wp
runtime: php
api_version: 1

handlers:
- url: /wp-content/themes/fuse/library/css/custom.css.php
  script: wordpress/wp-content/themes/fuse/library/css/custom.css.php

- url: /(.*\.(htm$|html$|css$|js$|ttf$|jpg$|jpeg$|otf$))
  static_files: wordpress/\1
  upload: wordpress/(.*\.(htm$|html$|css$|js$|ttf$|jpg$|jpeg$|otf$))
  application_readable: true

- url: /wp-content/(.*\.(ico$|jpg$|png$|gif$|ttf$|jpeg$|htm$|html$|css$|js$|otf$))
  static_files: wordpress/wp-content/\1
  upload: wordpress/wp-content/(.*\.(ico$|jpg$|png$|gif$|ttf$|jpeg$|htm$|html$|css$|js$|otf$))
  application_readable: true

- url: /(.*\.(ico$|jpg$|png$|gif$|ttf$|jpeg$|htm$|html$|css$|js$|otf$))
  static_files: wordpress/\1
  upload: wordpress/(.*\.(ico$|jpg$|png$|gif$|ttf$|jpeg$|htm$|html$|css$|js$|otf$))

- url: /wp-admin/(.+)
  script: wordpress/wp-admin/\1
  secure: always

- url: /wp-admin/
  script: wordpress/wp-admin/index.php
  secure: always

- url: /wp-login.php
  script: wordpress/wp-login.php
  secure: always

- url: /wp-cron.php
  script: wordpress/wp-cron.php
  login: admin

- url: /xmlrpc.php
  script: wordpress/xmlrpc.php

- url: /(.+)?/?
  script: wordpress/index.php